// day	exercise	Image	video Url
// "https://www.youtube.com/embed/";
const workout = [
  {
    day: "PUSH A",
    muscleGroup: "chest",
    exercise: "Flat Barbell Bench Press",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    muscleGroup: "chest",
    exercise: "Flat Barbell Bench Press",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    exercise: "Seated Barbell Shoulder Press",
        sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    exercise: "flat barbell bench press",
        sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    exercise: "flat barbell bench press",
        sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    exercise: "flat barbell bench press",
        sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    exercise: "flat barbell bench press",
        sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    exercise: "flat barbell bench press",
        sets: 5,
    repsPerSet: 3,
    restInSeconds: 90,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image: "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
];

export default workout;