// day	exercise	Image	video Url
// "https://www.youtube.com/embed/";
const workout = [
  {
    day: "PUSH A",
    muscleGroup: "chest",
    exercise: "Flat Barbell Bench Press",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90 - 120,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    muscleGroup: "shoulders",
    exercise: "Seated Neck Press",
    sets: 3,
    repsPerSet: 8,
    restInSeconds: 60,
    video: "https://youtube.com/embed/j7ULT6dznNc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    muscleGroup: "triceps",
    exercise: "Tricep Dips",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/6MwtkyNC2ZY",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    muscleGroup: "chest",
    exercise: "Cable Flys",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/WEM9FCIPlxQ",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    muscleGroup: "triceps",
    exercise: "Rope Pull Down",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/LzwgB15UdO8",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH A",
    muscleGroup: "shoulders",
    exercise: "Seated Dumbbell Lateral Raises",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/nOx4hDCiZJE",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL A",
    muscleGroup: "back",
    exercise: "Deadlift",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90 - 120,
    video: "https://www.youtube.com/embed/wjsu6ceEkAQ",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL A",
    muscleGroup: "back",
    exercise: "Chin-ups",
    sets: 3,
    repsPerSet: 8,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/1EJ3A3rEtlo",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL A",
    muscleGroup: "back",
    exercise: "Chest Supported Rows",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/WPpMRmgoe8I",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL A",
    muscleGroup: "back",
    exercise: "Lat Pull-downs",
    sets: 4,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/lueEJGjTuPQ",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL A",
    muscleGroup: "biceps",
    exercise: "Standing Dumbbell Curls",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/ykJmrZ5v0Oo",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL A",
    muscleGroup: "back",
    exercise: "Rope Bicep Curl",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/NFzTWp2qpiE",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Barbell Squat",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90 - 120,
    video: "https://www.youtube.com/embed/R2dMsNhN3DE",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Leg Press",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/sEM_zo9w2ss",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Calf Raise",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/Yh5TXz99xwY",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Leg Curl",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/ELOCsoDSmrg",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Leg Extension",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/0fl1RRgJ83I",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH B",
    muscleGroup: "shoulders",
    exercise: "Dumbell Shoulder Press",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90 - 120,
    video: "https://www.youtube.com/embed/qEwKCR5JCog",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH B",
    muscleGroup: "chest",
    exercise: "Incline Bench Press",
    sets: 3,
    repsPerSet: 8,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/uIzbJX5EVIY",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH B",
    muscleGroup: "chest",
    exercise: "Dumbell Flys",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/eozdVDA78K0",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH B",
    muscleGroup: "triceps",
    exercise: "Tricep Push-down (machine)",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/yPohcZXCZSc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH B",
    muscleGroup: "triceps",
    exercise: "Tricep Pushdown (Straight bar)",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/LzwgB15UdO8",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PUSH B",
    muscleGroup: "shoulders",
    exercise: "Standing Cable Lateral Raises",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/PPrzBWZDOhA",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "back",
    exercise: "T-Bar Rows",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 90 - 120,
    video: "https://youtube.com/embed/j3Igk5nyZE4",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "back",
    exercise: "Pull-ups",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://youtube.com/embed/5oxviYmdHCY",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "back",
    exercise: "Cable-Rows",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://youtube.com/embed/GZbfZ033f74",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "back",
    exercise: "Lat Pull-downs",
    sets: 4,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "biceps",
    exercise: "Barbell curls",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "biceps",
    exercise: "Seated Dumbbell Curls",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "PULL B",
    muscleGroup: "biceps",
    exercise: "Seated Dumbbell Curls (dropset)",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://youtube.com/embed/tuwHzzPdaGc",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Barbell Squat",
    sets: 5,
    repsPerSet: 3,
    restInSeconds: 90 - 120,
    video: "https://www.youtube.com/embed/R2dMsNhN3DE",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Leg Press",
    sets: 3,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/sEM_zo9w2ss",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Calf Raise",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 30,
    video: "https://www.youtube.com/embed/Yh5TXz99xwY",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Leg Curl",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/ELOCsoDSmrg",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
  {
    day: "LEGS A",
    muscleGroup: "legs",
    exercise: "Leg Extension",
    sets: 5,
    repsPerSet: 10,
    restInSeconds: 60,
    video: "https://www.youtube.com/embed/0fl1RRgJ83I",
    image:
      "https://images.everydayhealth.com/images/how-to-train-if-you-have-an-ectomorph-body-type-722x406.jpg?sfvrsn=16febb96_1",
  },
];

export default workout;
